version: '2.1'
services:
    account:
        build: ./services/account
        environment:
            namespace: "eostalk"
            steem_node: "https://rpc.buildteam.io"
        links:
            - mongo
        restart: on-failure
        volumes:
            - ./services/account:/src:rw
    mongodata:
        image: mongo:3.3.10
        volumes:
            - /Users/tuanpa/Work/eos/data/mongodata:/data/db
        command: --break-mongo
    mongo:
        image: mongo:3.3.10
        volumes:
            - ./:/tempo:rw
        volumes_from:
            - mongodata
        ports:
            - "27017:27017"
        command: --smallfiles --rest
    rest:
        build: ./services/rest
        environment:
            namespace: "eostalk"
        external_links:
            - mongo:forums_mongo_1
        ports:
            - "5000:5000"
        restart: on-failure
        volumes:
            - ./services/rest:/src:rw
    statistics:
        build: ./services/statistics/steem
        links:
            - mongo
        environment:
            namespace: "eostalk"
            steem_node: "https://rpc.buildteam.io"
        restart: on-failure
        volumes:
            - ./services/statistics/steem:/src:rw
    steem:
        build: ./services/indexer/steem
        environment:
            namespace: "eostalk"
            steem_node: "https://steem.chainbb.com"
        links:
            - mongo
        restart: on-failure
        volumes:
            - ./services/indexer/steem:/src:rw
